"""
AI 3D Asset Pipeline - Python Backend Entry Point

Week 1: Dummy pipeline that simulates five processing stages and generates
a placeholder textured cube as .obj + .mtl + texture.png, verifying the
full IPC round-trip between Unity and Python.

Usage:
    python main.py --video_path "path/to/video.mp4" --output_dir "path/to/output"

Optional:
    --click_x 0.5   Normalized X coordinate of user click (0.0-1.0)
    --click_y 0.5   Normalized Y coordinate of user click (0.0-1.0)
"""

import argparse
import os
import sys
import time

# Force UTF-8 on stdout/stderr to prevent Windows charmap encoding errors
if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

# Ensure we can import the pipeline package regardless of cwd
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from pipeline.ipc import report_progress, report_result, report_error, report_log


# ---------------------------------------------------------------------------
# Dummy asset generation
# ---------------------------------------------------------------------------

def generate_dummy_texture(output_dir: str, size: int = 256) -> str:
    """Generate a checkerboard texture PNG using Pillow (with stdlib fallback)."""
    texture_path = os.path.join(output_dir, "texture.png")

    try:
        from PIL import Image

        img = Image.new("RGB", (size, size), color=(100, 149, 237))
        pixels = img.load()
        for y in range(size):
            for x in range(size):
                if (x // 32 + y // 32) % 2 == 0:
                    pixels[x, y] = (100, 149, 237)   # Cornflower blue
                else:
                    pixels[x, y] = (70, 130, 180)     # Steel blue

        img.save(texture_path)
        report_log("Texture generated with Pillow")
        return texture_path

    except ImportError:
        # Fallback: build a minimal valid PNG without any third-party library
        report_log("Pillow not installed - creating minimal PNG via stdlib")

        import struct
        import zlib

        width, height = 4, 4
        raw_data = b""
        for y in range(height):
            raw_data += b"\x00"  # PNG filter byte (None)
            for x in range(width):
                if (x + y) % 2 == 0:
                    raw_data += bytes([100, 149, 237])
                else:
                    raw_data += bytes([70, 130, 180])

        def _make_chunk(chunk_type: bytes, data: bytes) -> bytes:
            crc = zlib.crc32(chunk_type + data) & 0xFFFFFFFF
            return struct.pack(">I", len(data)) + chunk_type + data + struct.pack(">I", crc)

        ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
        compressed = zlib.compress(raw_data)

        with open(texture_path, "wb") as f:
            f.write(b"\x89PNG\r\n\x1a\n")
            f.write(_make_chunk(b"IHDR", ihdr))
            f.write(_make_chunk(b"IDAT", compressed))
            f.write(_make_chunk(b"IEND", b""))

        return texture_path


def generate_dummy_obj(output_dir: str) -> tuple:
    """Generate a simple textured cube as OBJ + MTL files."""

    mtl_content = """\
# AI Asset Pipeline - Dummy Material
newmtl cube_material
Ka 0.2 0.2 0.2
Kd 0.8 0.8 0.8
Ks 0.5 0.5 0.5
Ns 100.0
d 1.0
illum 2
map_Kd texture.png
"""

    obj_content = """\
# AI Asset Pipeline - Dummy Cube
# Generated by Week 1 dummy pipeline
mtllib model.mtl

# Vertices
v -0.5 -0.5  0.5
v  0.5 -0.5  0.5
v  0.5  0.5  0.5
v -0.5  0.5  0.5
v -0.5 -0.5 -0.5
v  0.5 -0.5 -0.5
v  0.5  0.5 -0.5
v -0.5  0.5 -0.5

# Texture coordinates
vt 0.0 0.0
vt 1.0 0.0
vt 1.0 1.0
vt 0.0 1.0

# Normals
vn  0.0  0.0  1.0
vn  0.0  0.0 -1.0
vn  1.0  0.0  0.0
vn -1.0  0.0  0.0
vn  0.0  1.0  0.0
vn  0.0 -1.0  0.0

usemtl cube_material

# Front face
f 1/1/1 2/2/1 3/3/1 4/4/1
# Back face
f 6/1/2 5/2/2 8/3/2 7/4/2
# Right face
f 2/1/3 6/2/3 7/3/3 3/4/3
# Left face
f 5/1/4 1/2/4 4/3/4 8/4/4
# Top face
f 4/1/5 3/2/5 7/3/5 8/4/5
# Bottom face
f 5/1/6 6/2/6 2/3/6 1/4/6
"""

    obj_path = os.path.join(output_dir, "model.obj")
    mtl_path = os.path.join(output_dir, "model.mtl")

    with open(obj_path, "w") as f:
        f.write(obj_content)

    with open(mtl_path, "w") as f:
        f.write(mtl_content)

    return obj_path, mtl_path


# ---------------------------------------------------------------------------
# Dummy pipeline
# ---------------------------------------------------------------------------

STAGES = [
    ("Frame Extraction",    "Extracting keyframes from video...",              0.8),
    ("Segmentation",        "Segmenting target object in frames...",           1.0),
    ("3D Reconstruction",   "Reconstructing 3D mesh from segmented frames...", 1.2),
    ("Mesh Processing",     "Optimising mesh topology and UV mapping...",      0.8),
    ("Export",              "Generating final OBJ / MTL / texture files...",   0.5),
]


def run_dummy_pipeline(video_path: str, output_dir: str) -> None:
    """
    Simulate five pipeline stages with ``time.sleep``, then generate
    a dummy textured cube (.obj + .mtl + texture.png).
    """
    report_log(f"Pipeline started - video: {video_path}")
    report_log(f"Output directory: {output_dir}")

    os.makedirs(output_dir, exist_ok=True)

    total = len(STAGES)

    for i, (name, msg, duration) in enumerate(STAGES):
        base = i / total
        report_progress(base, name, f"Starting {name}...")
        report_log(msg)

        steps = 5
        for step in range(steps):
            time.sleep(duration / steps)
            frac = base + ((step + 1) / steps) * (1.0 / total)
            report_progress(frac, name, msg)

        report_log(f"[OK] {name} complete")

    # ---- Generate dummy files ------------------------------------------------
    report_log("Writing dummy cube mesh...")
    obj_path, mtl_path = generate_dummy_obj(output_dir)
    report_log(f"Created: {os.path.basename(obj_path)}")
    report_log(f"Created: {os.path.basename(mtl_path)}")

    report_log("Writing texture...")
    texture_path = generate_dummy_texture(output_dir)
    report_log(f"Created: {os.path.basename(texture_path)}")

    # ---- Report result -------------------------------------------------------
    report_progress(1.0, "Complete", "Pipeline finished successfully!")
    report_result(
        {
            "status": "success",
            "mesh_path": os.path.abspath(obj_path),
            "mtl_path": os.path.abspath(mtl_path),
            "texture_path": os.path.abspath(texture_path),
            "output_dir": os.path.abspath(output_dir),
        }
    )


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="AI 3D Asset Pipeline - Python Backend",
    )
    parser.add_argument(
        "--video_path", type=str, required=True,
        help="Path to the input video file",
    )
    parser.add_argument(
        "--output_dir", type=str, required=True,
        help="Directory to save generated assets",
    )
    parser.add_argument(
        "--click_x", type=float, default=0.5,
        help="Normalised X coordinate of user click (0.0-1.0)",
    )
    parser.add_argument(
        "--click_y", type=float, default=0.5,
        help="Normalised Y coordinate of user click (0.0-1.0)",
    )

    args = parser.parse_args()

    # Week 1 doesn't actually read the video — just warn if missing
    if not os.path.exists(args.video_path):
        report_log(f"Warning: Video file not found: {args.video_path}")
        report_log("Week 1 dummy pipeline will proceed anyway.")

    try:
        run_dummy_pipeline(args.video_path, args.output_dir)
    except Exception as exc:
        report_error(f"Pipeline failed: {exc}")
        sys.exit(1)


if __name__ == "__main__":
    main()
